FROM opensuse/leap:15.1

RUN zypper ar -f \
        http://ftp.gwdg.de/pub/opensuse/repositories/multimedia:/libs/openSUSE_Leap_15.1/ \
        opensuse-multimedia-libs

RUN zypper --gpg-auto-import-keys refresh

RUN zypper --non-interactive install alsa-devel autoconf automake bluez-devel boost-devel \
        capi4linux-devel ccache cmake doxygen flac-devel fribidi-devel fstrcmp-devel gcc \
        gcc-c++ gettext-devel giflib-devel glew-devel gperf java-openjdk libass-devel \
        libavahi-devel libbluray-devel libbz2-devel libcap-devel libcap-ng-devel libcdio-devel \
        libcec-devel libcurl-devel libdvdread-devel libgudev-1_0-devel libidn2-devel \
        libjasper-devel libjpeg-devel liblcms2-devel libmad-devel libmicrohttpd-devel \
        libmodplug-devel libmpeg2-devel libmysqlclient-devel libnfs-devel libogg-devel \
        libpcap-devel libplist-devel libpng12-devel libpulse-devel libsamplerate-devel \
        libsmbclient-devel libtag-devel libtiff-devel libtool libudev-devel libuuid-devel \
        libva-devel libvdpau-devel libvorbis-devel libXrandr-devel libXrender-devel \
        libxslt-devel lirc-devel lzo-devel make Mesa-libEGL-devel Mesa-libGLESv2-devel \
        Mesa-libGLESv3-devel nasm patch pcre-devel python-devel randrproto-devel \
        renderproto-devel shairplay-devel sqlite3-devel swig tinyxml-devel

# Clone and build
RUN git clone https://github.com/xbmc/xbmc kodi && \
    cd kodi                                     && \
    mkdir build && cd $_                        && \
    cmake ..                                    && \
    make -j4
